
import type { Property } from '../types';

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    codigo: 'AP001',
    title: 'Apartamento Moderno no Centro',
    description: 'Um apartamento elegante e moderno com vistas deslumbrantes da cidade. Perfeito para quem busca conforto e conveniência.',
    type: 'apartamento',
    price: 450000,
    bedrooms: 2,
    bathrooms: 2,
    vagas: 1,
    area_m2: 90,
    address: 'Rua das Acácias, 1500',
    city: 'Americana',
    neighborhood: 'Centro',
    latitude: -22.7393,
    longitude: -47.3307,
    images: [
      'https://picsum.photos/seed/prop1-1/800/600',
      'https://picsum.photos/seed/prop1-2/800/600',
      'https://picsum.photos/seed/prop1-3/800/600',
    ],
    status: 'disponivel',
    finalidade: 'venda',
    featured: true,
    score: {
      location: 95,
      costBenefit: 80,
      appreciation: 88,
      analysis: 'Localização premium com alto potencial de valorização. O custo-benefício é bom, considerando a área e as comodidades.'
    }
  },
  {
    id: '2',
    codigo: 'CA002',
    title: 'Casa Espaçosa com Quintal e Piscina',
    description: 'Casa ideal para famílias, com amplo espaço externo, piscina e área de churrasco. Um refúgio de tranquilidade.',
    type: 'casa',
    price: 3500,
    bedrooms: 4,
    bathrooms: 3,
    vagas: 4,
    area_m2: 250,
    address: 'Rua das Flores, 123',
    city: "Santa Bárbara d'Oeste",
    neighborhood: 'Mollon',
    latitude: -22.7550,
    longitude: -47.4143,
    images: [
      'https://picsum.photos/seed/prop2-1/800/600',
      'https://picsum.photos/seed/prop2-2/800/600',
      'https://picsum.photos/seed/prop2-3/800/600',
    ],
    status: 'disponivel',
    finalidade: 'aluguel',
    featured: true,
    score: {
      location: 85,
      costBenefit: 92,
      appreciation: 90,
      analysis: 'Excelente custo-benefício pelo tamanho e lazer. Bairro em constante desenvolvimento com grande potencial de valorização.'
    }
  },
  {
    id: '3',
    codigo: 'KN003',
    title: 'Kitnet Aconchegante Próximo à FAM',
    description: 'Kitnet funcional e bem localizada, perfeita para estudantes ou jovens profissionais. Totalmente mobiliada e pronta para morar.',
    type: 'kitnet',
    price: 900,
    bedrooms: 1,
    bathrooms: 1,
    vagas: 0,
    area_m2: 35,
    address: 'Rua do Saber, 42',
    city: 'Americana',
    neighborhood: 'Vila Cordenonsi',
    latitude: -22.748,
    longitude: -47.32,
    images: [
      'https://picsum.photos/seed/prop3-1/800/600',
      'https://picsum.photos/seed/prop3-2/800/600',
    ],
    status: 'alugado',
    finalidade: 'aluguel',
    featured: false,
    score: {
      location: 90,
      costBenefit: 88,
      appreciation: 75,
      analysis: 'Ótima localização para o público universitário. Custo-benefício muito bom para a região. Valorização moderada.'
    }
  },
   {
    id: '4',
    codigo: 'AP004',
    title: 'Cobertura Duplex com Vista Panorâmica',
    description: 'Luxuosa cobertura com piscina privativa e vista de 360 graus. Acabamentos de alto padrão e design exclusivo.',
    type: 'apartamento',
    price: 1800000,
    bedrooms: 3,
    bathrooms: 4,
    vagas: 3,
    area_m2: 320,
    address: 'Av. Brasil, 900',
    city: 'Americana',
    neighborhood: 'Jardim Girassol',
    latitude: -22.73,
    longitude: -47.31,
    images: [
      'https://picsum.photos/seed/prop4-1/800/600',
      'https://picsum.photos/seed/prop4-2/800/600',
      'https://picsum.photos/seed/prop4-3/800/600',
    ],
    status: 'disponivel',
    finalidade: 'venda',
    featured: true,
    score: {
      location: 98,
      costBenefit: 75,
      appreciation: 95,
      analysis: 'Imóvel de altíssimo padrão em uma das localizações mais desejadas. Potencial de valorização garantido.'
    }
  },
  {
    id: '5',
    codigo: 'CA005',
    title: 'Casa de Condomínio com Lazer Completo',
    description: 'More com segurança e qualidade de vida. Casa em condomínio fechado com academia, quadras e salão de festas.',
    type: 'casa',
    price: 980000,
    bedrooms: 3,
    bathrooms: 3,
    vagas: 2,
    area_m2: 180,
    address: 'Rua da Tranquilidade, 5000',
    city: 'Nova Odessa',
    neighborhood: 'Jardim dos Lagos',
    latitude: -22.77,
    longitude: -47.29,
    images: [
      'https://picsum.photos/seed/prop5-1/800/600',
      'https://picsum.photos/seed/prop5-2/800/600',
      'https://picsum.photos/seed/prop5-3/800/600',
    ],
    status: 'vendido',
    finalidade: 'venda',
    featured: false,
    score: {
      location: 88,
      costBenefit: 85,
      appreciation: 82,
      analysis: 'Ideal para famílias que buscam segurança e lazer. Bom custo-benefício para a região. Valorização constante.'
    }
  },
   {
    id: '6',
    codigo: 'AP006',
    title: 'Apartamento de 1 Quarto perto da Rodoviária',
    description: 'Praticidade e mobilidade. Apartamento compacto e moderno a poucos passos do terminal rodoviário.',
    type: 'apartamento',
    price: 1500,
    bedrooms: 1,
    bathrooms: 1,
    vagas: 1,
    area_m2: 45,
    address: 'Rua das Viagens, 2000',
    city: "Santa Bárbara d'Oeste",
    neighborhood: 'Vila Siqueira Campos',
    latitude: -22.75,
    longitude: -47.40,
    images: [
      'https://picsum.photos/seed/prop6-1/800/600',
      'https://picsum.photos/seed/prop6-2/800/600',
    ],
    status: 'disponivel',
    finalidade: 'aluguel',
    featured: false,
    score: {
      location: 92,
      costBenefit: 85,
      appreciation: 80,
      analysis: 'Localização estratégica para quem precisa de mobilidade. Ótimo para investimento e aluguel.'
    }
  },
];